#!/bin/sh

#preselection='pt_1>23&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&tauDecayMode!=5&&tauDecayMode!=6&&tauDecayMode==5'
preselection='pt_1>24&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&tauDecayMode!=5&&tauDecayMode!=6&&tauIsoMedium>0.5'
inclselection='pt_1>24&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&tauDecayMode!=5&&tauDecayMode!=6&&tauIsoMedium>0.5'
#wreselection='pt_1>23&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&tauDecayMode!=5&&tauDecayMode!=6&&tauElectronTightMVA5&&againstMuonLoose3_2&&tau'
#inclselection='pt_1>23&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&tauDecayMode!=5&&tauDecayMode!=6&&tauDecayMode==5'
inclselection='pt_1>23&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&tauDecayMode!=5&&tauDecayMode!=6'
#inclselection='pt_1>23&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&tauDecayMode!=5&&tauDecayMode!=6&&((neutralIsoPtSum_2+chargedIsoPtSum_2)/pt_2)<.1'
wselection='mt_1>80'
signalselection='mt_1<40'
#qcdselection='pt_1>23&&pt_2>20&&vertices>0&&byCombinedIsolationDeltaBetaCorrRaw3Hits_2>1&&iso_1>0.01&&abs(q_2)==1'
#qcdselection='pt_1>23&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.1&&byCombinedIsolationDeltaBetaCorrRaw3Hits_2<1.5&&tightElectrons<=1&&tightMuons==0&&againstMuonLoose3_2&&tauElectronTightMVA5'
#qcdselection='pt_1>23&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.9&&tauIso<10'
#qcdselection='pt_1>18&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&againstMuonLoose3_2&&tauElectronTightMVA5'
#qcdselection='pt_1>18&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&tauDecayMode!=5&&tauDecayMode!=6&&againstMuonLoose3_2&&tauElectronTightMVA5&&tauDecayMode==5'
qcdselection='pt_1>18&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&againstMuonLoose3_2&&tauElectronTightMVA5&&tauDecayMode!=5&&tauDecayMode!=6'
qcdselectionAntiIso='pt_1>18&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&againstMuonLoose3_2&&tauElectronTightMVA5&&tauDecayMode!=5&&tauDecayMode!=6'
#qcdselectionAntiIso='pt_1>18&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<1&&tauIso<1.5&&tightElectrons<=2&&tightMuons<=1&&againstMuonLoose3_2&&tauElectronTightMVA5'
#qcdselectionAntiIso='pt_1>23&&pt_2>20&&vertices>0&&diLeptons==0&&tauIso<10&&iso_1<0.9'
trigselection='(lTrigger_25ns_sync)' #only for MC
trigselectiondata='(lTrigger_25ns_sync||lTrigger_25ns_23)' #only for MC
#qcdselection='pt_1>18&&pt_2>20&&npv>0&&diLeptons==0&&byCombinedIsolationDeltaBetaCorrRaw3Hits_2<10&&iso_1>0.1&&iso_1<0.9&&charge!=0&&abs(q_2)==1'
#relaxedSelection='pt1>23&&pt2>20&&vertices>0'
#embWeight='__CORR__*EmbPtWeight*HLT_Mu17_Mu8_fired'
luminosity=2094 #pb
direc='/nfs_scratch/laura/ztt_unweighted14_Golden/'
datadirec='/nfs_scratch/laura/ztt_unweighted16_Golden/'
zttScale=1.
qcdfactor=0 #Make 0 for Mc yiled
topSF=1.
bins=30
#
#binning='binningHighStat=0.,10.,20.,30.,40.,50.,60.,70.,80.,90.,100.,110.,120.,130.,140.,150.,160.,170.,180.,190.,200.,225.,250.,275.,300.,325.,350. binningLowStat=0.,20.,40.,60.,80.,100.,120.,140.,160.,210.,300.' 
binning='binningHighStat=0.,10.,20.,30.,40.,50.,60.,70.,80.,90.,100.,110.,120.,130.,140.,150.,160.,170.,180.,190.,200.,225.,250.,275.,300.,325.,350. binningLowStat=0.,20.,40.,60.,80.,100.,120.,140.,160.,180.,200.,250.,300.,350.' 
mkdir eleTauPlots

MakeDataCardZTT_MC channel='eleTau' dataFile=$datadirec'eleDATA.root' qcdFile=$direc'eleDATA.root' zttFile=$direc'ZJetsMerge.root' zllFile=$direc'ZJetsMerge.root' wFile=$direc'WJetsMLM.root' vvFile=$direc'VV.root' topFile=$direc'TT.root' inclselection=$inclselection preselection=$preselection  wselection=$wselection trigselection=$trigselection trigselection50ns=$trigselectiondata  signalselection=$signalselection   qcdselection=$qcdselection luminosityErr=0.045 qcdfactor=$qcdfactor qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075  topSF=$topSF 	muID=1.00 muIDErr=0.01 eleID=0.0 eleIDErr=0.0 tauID=1.0 tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17    bitmask=1,0,0,0 weight='__WEIGHT__*GENWEIGHT'  luminosity=$luminosity  variable='m_vis' bins=40 min=0 max=200 outputFile='eleTauPlots/eleTau_m_vis.root' 

MakeDataCardZTT_MC channel='eleTau' dataFile=$datadirec'eleDATA.root' qcdFile=$direc'eleDATA.root' zttFile=$direc'ZJetsMerge.root' zllFile=$direc'ZJetsMerge.root' wFile=$direc'WJetsMLM.root' vvFile=$direc'VV.root' topFile=$direc'TT.root' inclselection=$inclselection preselection=$preselection  wselection=$wselection trigselection=$trigselection trigselection50ns=$trigselectiondata  signalselection='mt_1<500'   qcdselection=$qcdselectionAntiIso luminosityErr=0.045 qcdfactor=$qcdfactor qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075  topSF=$topSF 	muID=1.00 muIDErr=0.01 eleID=0.0 eleIDErr=0.0 tauID=1.0 tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17    bitmask=1,0,0,0 weight='__WEIGHT__*GENWEIGHT'  luminosity=$luminosity  variable='mt_1' bins=40 min=0 max=200 outputFile='eleTauPlots/eleTau_mt_1.root' 
exit;
