#!/bin/sh
mkdir /nfs_scratch/$USER/LTau_Nov5
cd /nfs_scratch/$USER/LTau_Nov5

#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files    W_1.root /hdfs/store/user/ojalvo/WJets_v1-SUB-MCW &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files    W_2.root /hdfs/store/user/ojalvo/WJets_v2-SUB-MCW &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files  Z.root /hdfs/store/user/ojalvo/DYJets-SUB-MCZ & 
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files  Z1JETS.root /hdfs/store/user/ojalvo/Z1Jets-SUB-MCZ &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files  Z2JETS.root /hdfs/store/user/ojalvo/Z2Jets-SUB-MCZ &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files  Z3JETS.root /hdfs/store/user/ojalvo/Z3Jets-SUB-MCZ &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files  Z4JETS.root /hdfs/store/user/ojalvo/Z4Jets-SUB-MCZ &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files    W1JETS_1.root /hdfs/store/user/ojalvo/W1Jets_1-SUB-MCW &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files    W2JETS_1.root /hdfs/store/user/ojalvo/W2Jets_1-SUB-MCW &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files    W3JETS_1.root /hdfs/store/user/ojalvo/W3Jets_1-SUB-MCW &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files    W4JETS.root /hdfs/store/user/laura/W4Jets-SUB-MCW &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files    W1JETS_2.root /hdfs/store/user/ojalvo/W1Jets_2-SUB-MCW &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files    W2JETS_2.root /hdfs/store/user/ojalvo/W2Jets_2-SUB-MCW &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files    W3JETS_2.root /hdfs/store/user/laura/W3Jets_2-SUB-MCW &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files    WZ-3L.root /hdfs/store/user/ojalvo/WZ3L-SUB-MC &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files    WW-2L.root /hdfs/store/user/ojalvo/WW2L-SUB-MC &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files   ZZ-4L.root /hdfs/store/user/ojalvo/ZZ4L-SUB-MC &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files    WZ-LLQQ.root /hdfs/store/user/ojalvo/WZ2L2Q-SUB-MC & 
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files    ZZ-LLQQ.root /hdfs/store/user/ojalvo/ZZ2L2Q-SUB-MC &
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files    ZZ-LLVV.root /hdfs/store/user/ojalvo/ZZ2L2V-SUB-MC
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files     tW.root /hdfs/store/user/ojalvo/t_tW-SUB-MC 
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files     tBarW.root /hdfs/store/user/ojalvo/tBar_tW-SUB-MC 
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files   TOPNS.root /hdfs/store/user/ojalvo/TTBar-SUB-MC 
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files   TT_LL.root /hdfs/store/user/ojalvo/TTBar_LL-SUB-MC 
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files   TT_HL.root /hdfs/store/user/ojalvo/TTBar_HL-SUB-MC 
#nohup /cms/sw/farmout/mergeFiles --reuse-cache-files   TT_HH.root /hdfs/store/user/ojalvo/TTBar_HH-SUB-MC 

#cp Z.root ZJETSNS.root

#mkdir unweighted
#cp *.root unweighted/.
exit;
