#!/bin/sh

cd /scratch/ojalvo/LTau_113
W=1;Z=1;TOP=1;VV=1;

nohup mergeFiles --merge-only  --copy-timeout=90 ZJETS.root /hdfs/store/user/$USER/DYJets-SUB-MC &
nohup mergeFiles --merge-only  --copy-timeout=90 W_1.root /hdfs/store/user/$USER/WJets_v1-SUB-MC &
nohup mergeFiles --merge-only  --copy-timeout=90 W_2.root /hdfs/store/user/$USER/WJets_v2-SUB-MC &
nohup mergeFiles --merge-only   --copy-timeout=90 W1JETS.root /hdfs/store/user/$USER/W1Jets-SUB-MC &
nohup mergeFiles --merge-only   --copy-timeout=90 W2JETS.root /hdfs/store/user/$USER/W2Jets-SUB-MC &
nohup mergeFiles --merge-only   --copy-timeout=90 W3JETS.root /hdfs/store/user/$USER/W3Jets-SUB-MC &
nohup mergeFiles --merge-only   --copy-timeout=90 W4JETS.root /hdfs/store/user/$USER/W4Jets-SUB-MC &
nohup mergeFiles --merge-only  --copy-timeout=90 TOP.root /hdfs/store/user/$USER/TTBar-SUB-MC &
mergeFiles --merge-only  --copy-timeout=90 WZ-3L.root /hdfs/store/user/$USER/WZ3L-SUB-MC
nohup mergeFiles --merge-only  --copy-timeout=90 WW-2L.root /hdfs/store/user/$USER/WW2L-SUB-MC &
nohup mergeFiles  --copy-timeout=90 ZZ-4L.root /hdfs/store/user/$USER/ZZ4L-SUB-MC &
nohup mergeFiles   --copy-timeout=90 WZ-LLQQ.root /hdfs/store/user/$USER/WZ2L2Q-SUB-MC &
nohup mergeFiles --merge-only  --copy-timeout=90 ZZ-LLQQ.root /hdfs/store/user/$USER/ZZ2L2Q-SUB-MC &
#mergeFiles   --copy-timeout=90 ZZ-LLVV.root /hdfs/store/user/$USER/ZZ2L2V-SUB-MC
mergeFiles --merge-only   --copy-timeout=90 tW.root /hdfs/store/user/$USER/t_tW-SUB-MC
mergeFiles --merge-only   --copy-timeout=90 tBarW.root /hdfs/store/user/$USER/tBar_tW-SUB-MC
nohup mergeFiles --merge-only   --copy-timeout=90 TT_LL.root /hdfs/store/user/$USER/TTBar_LL-SUB-MC &
nohup mergeFiles --merge-only   --copy-timeout=90 TT_HH.root /hdfs/store/user/$USER/TTBar_HH-SUB-MC &
nohup mergeFiles --merge-only   --copy-timeout=90 TT_HL.root /hdfs/store/user/$USER/TTBar_HL-SUB-MC &

mkdir /scratch/ojalvo/unweighted
cp /scratch/ojalvo/LTau_113/* /scratch/ojalvo/unweighted/.

if [ -e W_1.root ] && [ -e W_2.root ] && [ $W -eq 1 ]
    then
    hadd W.root W_1.root W_2.root
else
    echo " Error in WJETS merging " > logMerge
fi

if [ -e ZJETS.root ] && [ $Z -eq 1 ]
    then
    EventWeightsIterative outputFile='ZJETS.root'   doOneD=1   weight=3504   type=3 histoName='MT/results'
    EventWeightsForEfficiencyFast $1 outputFile='ZJETS.root' 
    EventWeightsForEfficiencyZEE $1 outputFile='ZJETS.root' 
else
    echo " Error in ZJETS merging " >> logMerge

fi

if [ -e W.root ] && [ -e W1JETS.root ] && [ -e W2JETS.root  ] && [ -e W3JETS.root  ] && [ -e W4JETS.root  ] && [ $W -eq 1 ]
    then
    EventWeightsIterativeWJets       doOneD=1   weight=36257   type=4 histoName='MT/results'

    hadd WJETS.root W.root W1JETS.root W2JETS.root W3JETS.root W4JETS.root
    EventWeightsForEfficiencyFastWJets $1 outputFile='WJETS.root'
else
    echo " Error in W merging " >> logMerge
fi

if [ -e TOP.root ] && [ -e TT_LL.root ] && [ -e TT_HH.root ] && [ -e TT_HL.root ] && [ $TOP -eq 1 ]
    then
    EventWeightsIterative outputFile='TOP.root'      doOneD=1   weight=225.2    type=6 histoName='MT/results'
    EventWeightsIterative outputFile='TT_LL.root'      doOneD=1   weight=26.2    type=6 histoName='MT/results'
    EventWeightsIterative outputFile='TT_HH.root'      doOneD=1   weight=114    type=6 histoName='MT/results'
    EventWeightsIterative outputFile='TT_HL.root'      doOneD=1   weight=109.3    type=6 histoName='MT/results'
    hadd  TOP.root TT_LL.root TT_HH.root TT_HL.root 
    EventWeightsForEfficiencyFast $1 outputFile='TOP.root'
else
    echo " Error in TOP merging " >> logMerge
fi

if [ -e WW-2L.root ] && [ -e WZ-3L.root ] && [ -e ZZ-4L.root ] && [ -e WZ-LLQQ.root ] && [ -e ZZ-LLQQ.root ] && [ -e tW.root ] && [ -e tBarW.root ] && [ $VV -eq 1 ]
    then
    EventWeightsIterative outputFile='WW-2L.root'   doOneD=1   weight=5.824    type=7 histoName='MT/results'
    EventWeightsIterative outputFile='WZ-3L.root'   doOneD=1   weight=1.058   type=7 histoName='MT/results'
    EventWeightsIterative outputFile='ZZ-4L.root'   doOneD=1   weight=0.181    type=7  histoName='MT/results'
#EventWeightsIterative outputFile='ZZ-LLVV.root' doOneD=1   weight=0.716    type=7  histoName='MT/results'
    EventWeightsIterative outputFile='WZ-LLQQ.root' doOneD=1   weight=2.207    type=7 histoName='MT/results' 
    EventWeightsIterative outputFile='ZZ-LLQQ.root' doOneD=1   weight=2.502    type=7 histoName='MT/results'
    EventWeightsIterative outputFile='tW.root'  	doOneD=1   weight=11.1    type=6 histoName='MT/results' 
    EventWeightsIterative outputFile='tBarW.root'  	doOneD=1   weight=11.1    type=6 histoName='MT/results' 
    hadd VV.root WW-2L.root WZ-3L.root  ZZ-LLQQ.root WZ-LLQQ.root tW.root tBarW.root ZZ-4L.root ZZ-LLQQ.root
    EventWeightsForEfficiencyFast $1 outputFile='VV.root'
else
    echo " Error in VV region " >> logMerge
fi

#rm W.root W1JETS.root W2JETS.root W3JETS.root W4JETS.root 
#rm WW-2L.root WZ-3L.root ZZ-4L.root ZZ-LLQQ.root WZ-LLQQ.root tW.root tBarW.root













