#!/bin/sh
voms-proxy-init --voms cms --valid 100:00

cat GenStudy.py > SUB-GEN.py
cat CONDORPT.py >> SUB-GEN.py

cat LTJets.py > SUB-Jets.py
cat CONDORPT.py >> SUB-Jets.py

farmoutAnalysisJobs  $1   --vsize-limit=8000  --input-dir=/store/user/ojalvo/GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM/2014-8/ ggHhhttbb260 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LTau/SUB-MCH.py  
farmoutAnalysisJobs  $1   --vsize-limit=8000  --input-dir=/store/user/ojalvo/GluGluToHTohhTo2Tau2B_mH-300_mh-125_8TeV-pythia6-tauola/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM/2014-8/ ggHhhttbb300 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LTau/SUB-MCH.py  
farmoutAnalysisJobs  $1   --vsize-limit=8000  --input-dir=/store/user/ojalvo/GluGluToHTohhTo2Tau2B_mH-350_mh-125_8TeV-pythia6-tauola/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM/2014-8/ ggHhhttbb350 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LTau/SUB-MCH.py  
#farmoutAnalysisJobs  $1   --vsize-limit=8000  --input-dir=/hdfs/store/user/stephane/2014-02-20_PatTuples/H-hh-ttbb-MA260-TB5-PU025  ggHhhFS260 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LTau/SUB-MCH.py  
#farmoutAnalysisJobs  $1   --vsize-limit=8000  --input-dir=/hdfs/store/user/stephane/2014-02-20_PatTuples/H-hh-ttbb-MA270-TB5-PU025  ggHhhFS270 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LTau/SUB-MCH.py  
#farmoutAnalysisJobs  $1   --vsize-limit=8000  --input-dir=/hdfs/store/user/stephane/2014-02-20_PatTuples/H-hh-ttbb-MA280-TB5-PU025  ggHhhFS280 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LTau/SUB-MCH.py  
#farmoutAnalysisJobs  $1   --vsize-limit=8000  --input-dir=/hdfs/store/user/stephane/2014-02-20_PatTuples/H-hh-ttbb-MA290-TB5-PU025  ggHhhFS290 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LTau/SUB-MCH.py  
#farmoutAnalysisJobs  $1   --vsize-limit=8000  --input-dir=/hdfs/store/user/stephane/2014-02-20_PatTuples/H-hh-ttbb-MA300-TB5-PU025  ggHhhFS300 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LTau/SUB-MCH.py  
#farmoutAnalysisJobs  $1   --vsize-limit=8000  --input-dir=/hdfs/store/user/stephane/2014-02-20_PatTuples/H-hh-ttbb-MA310-TB5-PU025  ggHhhFS310 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LTau/SUB-MCH.py  
#farmoutAnalysisJobs  $1   --vsize-limit=8000  --input-dir=/hdfs/store/user/stephane/2014-02-20_PatTuples/H-hh-ttbb-MA320-TB5-PU025  ggHhhFS320 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LTau/SUB-MCH.py  
#farmoutAnalysisJobs  $1   --vsize-limit=8000  --input-dir=/hdfs/store/user/stephane/2014-02-20_PatTuples/H-hh-ttbb-MA330-TB5-PU025  ggHhhFS330 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LTau/SUB-MCH.py  
#farmoutAnalysisJobs  $1   --vsize-limit=8000  --input-dir=/hdfs/store/user/stephane/2014-02-20_PatTuples/H-hh-ttbb-MA340-TB5-PU025  ggHhhFS340 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LTau/SUB-MCH.py  



rm SUB-Jets.py
rm SUB-GEN.py

#farmoutAnalysisJobs  $1   --vsize-limit=8000  --input-dir=/store/user/ojalvo/GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola/  ggHhh260 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LTau/SUB-Jets.py  
#farmoutAnalysisJobs  $1   --vsize-limit=8000  --input-dir=/store/user/ojalvo/GluGluToHTohhTo2Tau2B_mH-300_mh-125_8TeV-pythia6-tauola/  ggHhh300 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LTau/SUB-Jets.py  
#farmoutAnalysisJobs  $1   --vsize-limit=8000  --input-dir=/store/user/ojalvo/GluGluToHTohhTo2Tau2B_mH-350_mh-125_8TeV-pythia6-tauola/  ggHhh350 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LTau/SUB-Jets.py  
