#!/bin/sh
voms-proxy-init --voms cms --valid 100:00

cat MNu-MCPatMC.py  > MuNuPAT.py
cat CONDORPT.py >> MuNuPAT.py
#--output-dag-file=/scratch/ojalvo/DAGs/$1/WJets
farmoutAnalysisJobs --input-files-per-job=1 --skip-existing-output --output-dir=. --input-dbs-path=/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/cepeda-WplusJets_madgraph_2012-05-29-7TeV-PatTuple-67c1f94-98f6272e3f90a8dc5047059cf7088f10/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet W $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

#farmoutAnalysisJobs $1 --input-files-per-job=2 --use-osg --vsize-limit=5000 --use-osg --express-queue --output-dir=/store/user/ojalvo --input-dbs-path=/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM WJets $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

farmoutAnalysisJobs $1 --input-files-per-job=1 --output-dir=. --input-dbs-path=/T_TuneZ2_t-channel_7TeV-powheg-tauola/cepeda-T_t_Powheg_2012-05-29-7TeV-PatTuple-67c1f94-5112c7af8b9b76ce11f7741050a95cb0/USER  --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet T $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py 

##farmoutAnalysisJobs $1 --vsize-limit=5000 --use-osg --express-queue --input-files-per-job=5 --output-dir=. --input-dbs-path=/Tbar_TuneZ2_t-channel_7TeV-powheg-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM  Tbar  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py 
##farmoutAnalysisJobs $1 --vsize-limit=5000 --use-osg --express-queue --input-files-per-job=5 --output-dir=. --input-dbs-path=/T_TuneZ2_tW-channel-DR_7TeV-powheg-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM  TtWDR  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py 

farmoutAnalysisJobs $1 --input-files-per-job=1 --output-dir=. --input-dbs-path=/T_TuneZ2_s-channel_7TeV-powheg-tauola/cepeda-T_s_Powheg_2012-05-29-7TeV-PatTuple-67c1f94-450d31a5f472997d9c8d4351cbe01109/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet Ts $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py 

##farmoutAnalysisJobs $1 --vsize-limit=5000 --use-osg --express-queue --input-files-per-job=5 --output-dir=. --input-dbs-path=/Tbar_TuneZ2_s-channel_7TeV-powheg-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM Tbars $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py 

farmoutAnalysisJobs $1 --input-files-per-job=1 --output-dir=. --input-dbs-path=/DYJetsToLL_TuneZ2_M-50_7TeV-madgraph-tauola/cepeda-Zjets_M50_2012-05-29-7TeV-PatTuple-67c1f94-e7c083b3facfba2612ce8e9d30894d70/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DYall $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py 

farmoutAnalysisJobs $1 --input-files-per-job=1 --output-dir=. --input-dbs-path=/QCD_Pt-20_MuEnrichedPt-15_TuneZ2_7TeV-pythia6/swanson-QCD_20toInf_MuPt15_2012_5_30_7TeV-67c1f94-43f96022639e7ed5e8b1f966bca466d1/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet QCDMu $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py 


farmoutAnalysisJobs $1 --input-files-per-job=1  --output-dir=. --input-dbs-path=/WZ_TuneZ2_7TeV_pythia6_tauola/friis-WZinclusive_2012-05-29-7TeV-PatTuple-v2-75d04f0-f4b7a22a460bc1adf1542bada508e434/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet WZ $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

##farmoutAnalysisJobs $1 --vsize-limit=5000 --use-osg --express-queue  --input-files-per-job=2  --output-dir=. --input-dbs-path=/ZZ_TuneZ2_7TeV_pythia6_tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM ZZ $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

farmoutAnalysisJobs $1 --input-files-per-job=1 --output-dir=. --input-dbs-path=/WW_TuneZ2_7TeV_pythia6_tauola/friis-WWinclusive_2012-05-29-7TeV-PatTuple-v2-75d04f0-522bff21575db58ce7449b44a836c79a/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet WW $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py

farmoutAnalysisJobs $1 --input-files-per-job=1 --output-dir=. --input-dbs-path=/TTJets_TuneZ2_7TeV-madgraph-tauola/iross-TTplusJets_madgraph_2012-05-29-7TeV-PatTuple-a-67c1f94-c6f177514202379f3acea419c647ad63/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet TOP $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/MuNuPAT.py 



rm MuNuPAT.py