#!/bin/sh

#preselection='pt_1>23&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&tauDecayMode!=5&&tauDecayMode!=6&&tauDecayMode==5'
preselection='pt_1>23&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&tauDecayMode!=5&&tauDecayMode!=6'
#inclselection='pt_1>23&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&tauDecayMode!=5&&tauDecayMode!=6&&tauDecayMode==5'
inclselection='pt_1>23&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&tauDecayMode!=5&&tauDecayMode!=6'
#inclselection='pt_1>23&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&tauDecayMode!=5&&tauDecayMode!=6&&((neutralIsoPtSum_2+chargedIsoPtSum_2)/pt_2)<.1'
wselection='mt_1>70'
signalselection='mt_1<40'
#qcdselection='pt_1>23&&pt_2>20&&vertices>0&&byCombinedIsolationDeltaBetaCorrRaw3Hits_2>1&&iso_1>0.01&&abs(q_2)==1'
#qcdselection='pt_1>23&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.1&&byCombinedIsolationDeltaBetaCorrRaw3Hits_2<1.5&&tightElectrons<=1&&tightMuons==0&&againstMuonLoose3_2&&tauElectronTightMVA5'
#qcdselection='pt_1>23&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<0.9&&tauIso<10'
#qcdselection='pt_1>18&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&againstMuonLoose3_2&&tauElectronTightMVA5'
#qcdselection='pt_1>18&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&tauDecayMode!=5&&tauDecayMode!=6&&againstMuonLoose3_2&&tauElectronTightMVA5&&tauDecayMode==5'
qcdselection='pt_1>18&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&againstMuonLoose3_2&&tauElectronTightMVA5&&tauDecayMode!=5&&tauDecayMode!=6'
qcdselectionAntiIso='pt_1>18&&pt_2>20&&vertices>0&&diLeptons==0&&iso_1<.1&&tauIso<1.5&&tightElectrons<=1&&tightMuons==0&&againstMuonLoose3_2&&tauElectronTightMVA5&&tauDecayMode!=5&&tauDecayMode!=6'
#trigselection='pt_1>23' #only for MC
#trigselectiondata='pt_1>23' #only for Data
trigselection='(crossTrigger>0||(lTrigger>0&&pt_1>33))' #only for MC
trigselectiondata='(crossTrigger_50ns>0||(lTrigger_50ns>0&&pt_1>33))' #only for Data
luminosity=166 #pb
direc='/nfs_scratch/laura/ztt_weighted9/'
zttScale=1.
qcdfactor=1.0
topSF=1.
bins=30
#
#binning='binningHighStat=0.,10.,20.,30.,40.,50.,60.,70.,80.,90.,100.,110.,120.,130.,140.,150.,160.,170.,180.,190.,200.,225.,250.,275.,300.,325.,350. binningLowStat=0.,20.,40.,60.,80.,100.,120.,140.,160.,210.,300.' 
binning='binningHighStat=0.,10.,20.,30.,40.,50.,60.,70.,80.,90.,100.,110.,120.,130.,140.,150.,160.,170.,180.,190.,200.,225.,250.,275.,300.,325.,350. binningLowStat=0.,20.,40.,60.,80.,100.,120.,140.,160.,180.,200.,250.,300.,350.' 
mkdir eleTauPlots

MakeDataCardZTT channel='eleTau' dataFile=$direc'eleDATA.root' qcdFile=$direc'emQCD.root.root' zttFile=$direc'ZJetsMerge.root' zllFile=$direc'ZJetsMerge.root' wFile=$direc'WJetsHTStitched.root' vvFile=$direc'VV.root' topFile=$direc'TTJets.root' inclselection=$inclselection preselection=$preselection  wselection=$wselection trigselection=$trigselection trigselection50ns=$trigselectiondata  signalselection=$signalselection   qcdselection=$qcdselection luminosityErr=0.045 qcdfactor=$qcdfactor qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075  topSF=$topSF 	muID=1.00 muIDErr=0.01 eleID=0.0 eleIDErr=0.0 tauID=1.0 tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17    bitmask=1,0,0,0 weight='__WEIGHT__*GENWEIGHT'  luminosity=$luminosity  variable='m_vis' bins=40 min=0 max=200 outputFile='eleTauPlots/eleTau_m_vis.root' 

