#!/bin/sh
#ZSkim contains all skim information for ZEE and ZMuMu skim
voms-proxy-init --voms cms --valid 100:00
cat MNu-MCCondor.py >WMuNu.py
#cat CONDOR.py >>WMuNu.py

#farmoutAnalysisJobs $1 --input-files-per-job=8  --input-dbs-path=/QCD_Pt-30to80_BCtoE_TuneZ2_7TeV-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM  QCDBC30  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/WMuNu.py 
farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM  W  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/WMuNu.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/QCD_Pt-30to80_EMEnriched_TuneZ2_7TeV-pythia/Fall11-PU_S6_START42_V14B-v1/AODSIM  QCDEM  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/WMuNu.py 
#farmoutAnalysisJobs $1 --input-files-per-job=3  --input-dbs-path=/DYJetsToLL_TuneZ2_M-50_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM  DYallPythia  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/WMuNu.py 

#farmoutAnalysisJobs $1 --input-files-per-job=10  --input-dbs-path=/TTJets_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v2/AODSIM  TOP  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/WMuNu.py 

#farmoutAnalysisJobs $1  --input-files-per-job=2 --output-dir=.  --input-dbs-path=/WZJetsTo2L2Q_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM WZ $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/WMuNu.py
#farmoutAnalysisJobs $1  --input-files-per-job=2 --output-dir=.  --input-dbs-path=/ZZ_TuneZ2_7TeV_pythia6_tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM ZZ $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/WMuNu.py

#farmoutAnalysisJobs $1  --input-files-per-job=2 --output-dir=.  --input-dbs-path=/WW_TuneZ2_7TeV_pythia6_tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM WW $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/MuNu/WMuNu.py

rm WMuNu.py