#!/bin/sh
voms-proxy-init --voms cms --valid 100:00

#PromptREco
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist --vsize-limit=8000 --skip-existing-output  --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016B-PromptReco-v2/MINIAOD SINGLEMUON2016B_SMHiggs_Oct21 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist --vsize-limit=8000 --skip-existing-output  --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016C-PromptReco-v2/MINIAOD SINGLEMUON2016C_SMHiggs_Oct21 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist --vsize-limit=8000 --skip-existing-output  --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016D-PromptReco-v2/MINIAOD SINGLEMUON2016D_SMHiggs_Oct21 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist --vsize-limit=8000 --skip-existing-output  --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016E-PromptReco-v2/MINIAOD SINGLEMUON2016E_SMHiggs_Oct21 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist --vsize-limit=8000 --skip-existing-output  --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016F-PromptReco-v1/MINIAOD SINGLEMUON2016F_SMHiggs_Oct21 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist --vsize-limit=8000 --skip-existing-output  --input-files-per-job=1 --input-dbs-path=/SingleMuon/Run2016G-PromptReco-v1/MINIAOD SINGLEMUON2016G_SMHiggs_Oct24 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSONG.py  

/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist --vsize-limit=8000 --skip-existing-output  --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016B-PromptReco-v2/MINIAOD SINGLEELE2016B_SMHiggs_Oct21 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist --vsize-limit=8000 --skip-existing-output  --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016C-PromptReco-v2/MINIAOD SINGLEELE2016C_SMHiggs_Oct21 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist --vsize-limit=8000 --skip-existing-output  --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016D-PromptReco-v2/MINIAOD SINGLEELE2016D_SMHiggs_Oct21 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist --vsize-limit=8000 --skip-existing-output  --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016E-PromptReco-v2/MINIAOD SINGLEELE2016E_SMHiggs_Oct21 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist --vsize-limit=8000 --skip-existing-output  --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016F-PromptReco-v1/MINIAOD SINGLEELE2016F_SMHiggs_Oct21 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSON.py  
/cms/sw/farmout/farmoutAnalysisJobs.fix  $1  --assume-input-files-exist --vsize-limit=8000 --skip-existing-output  --input-files-per-job=1 --input-dbs-path=/SingleElectron/Run2016G-PromptReco-v1/MINIAOD SINGLEELE2016G_SMHiggs_Oct24 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/SMHiggs/SUB-JSONG.py  
