#!/bin/sh

SUFFIX='-M Asymptotic --rMax=30'
PFIX='Asymptotic'
if [ $2 = "sig" ]; then
SUFFIX=' --signif --pvalue ' 
PFIX='ProfileLikelihood'

fi

for mass in 90  120 130 140 160 180 200 250 300 350 400 450 500
do
combine datacards/$1_mA$mass.txt  -m $mass $SUFFIX
done
find higgsCombineTest.$PFIX.mH* |xargs hadd $1-results.root
