#!/bin/sh
#ZSkim contains all skim information for ZEE and ZMuMu skim
voms-proxy-init --voms cms --valid 100:00
cat ZSkim.py >TPSKIM.py
#cat CONDOR.py >>TPSKIM.py
#farmoutAnalysisJobs $1 --input-files-per-job=10  --input-dbs-path=/QCD_Pt-20to30_EMEnriched_TuneZ2_7TeV-pythia6/Summer11-PU_S4_START42_V11-v1/AODSIM   QCDEM20  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 

#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/QCD_Pt-80to170_EMEnriched_TuneZ2_7TeV-pythia6/Summer11-PU_S4_START42_V11-v1/AODSIM   QCDEM80  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/QCD_Pt-20to30_BCtoE_TuneZ2_7TeV-pythia6/Summer11-PU_S3_START42_V11-v2/AODSIM   QCDBC20  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/QCD_Pt-30to80_BCtoE_TuneZ2_7TeV-pythia6/Summer11-PU_S4_START42_V11-v1/AODSIM   QCDBC30  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/QCD_Pt-80to170_BCtoE_TuneZ2_7TeV-pythia6/Spring11-PU_S1_START311_V1G1-v1/AODSIM   QCDBC80  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/DYToTauTau_M-20_TuneZ2_7TeV-pythia6-tauola/Summer11-PU_S3_START42_V11-v2/AODSIM ZTT $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/G_Pt-30to50_TuneZ2_7TeV_pythia6/Summer11-PU_S3_START42_V11-v2/AODSIM  G30  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 
###fall11
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/GluGluToHToZZTo2L2Q_M-230_7TeV-powheg-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM  H230  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/ZH_ZToLL_HToBB_M-130_7TeV-powheg-herwigpp/Summer11-PU_S4_START42_V11-v4/AODSIM  H130  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/ZbbToLL_M-50_TuneZ2_7TeV-madgraph-pythia6_tauola/Summer11-PU_S4_START42_V11-v1/AODSIM  ZBB  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM  W  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/TTJets_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM  TOP  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/WZ_TuneZ2_7TeV_pythia6_tauola/Summer11-PU_S4_START42_V11-v1/AODSIM WZ  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/WW_TuneZ2_7TeV_pythia6_tauola/Summer11-PU_S4_START42_V11-v1/AODSIM  WW  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/ZZ_TuneZ2_7TeV_pythia6_tauola/Summer11-PU_S4_START42_V11-v1/AODSIM  ZZ  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 
#farmoutAnalysisJobs $1 --input-files-per-job=3  --input-dbs-path=/DYJetsToLL_TuneZ2_M-50_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM   ZJETS  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 

farmoutAnalysisJobs $1 --input-files-per-job=8  --input-dbs-path=/QCD_Pt-30to80_BCtoE_TuneZ2_7TeV-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM  QCDEM30_New  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/TPSKIM.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/ZbbToLL_M-50_TuneZ2_7TeV-madgraph-pythia6_tauola/Fall11-PU_S6_START42_V14B-v2/AODSIM  ZBB  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/TPSKIM1.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM  W  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/TPSKIM1.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/TTJets_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v2/AODSIM  TOP  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/TPSKIM1.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/WZ_TuneZ2_7TeV_pythia6_tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM WZ  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/TPSKIM1.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/WW_TuneZ2_7TeV_pythia6_tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM  WW  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/TPSKIM1.py 
#farmoutAnalysisJobs $1 --input-files-per-job=5  --input-dbs-path=/ZZ_TuneZ2_7TeV_pythia6_tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM  ZZ  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/TPSKIM1.py 
#farmoutAnalysisJobs $1 --input-files-per-job=3  --input-dbs-path=/DYJetsToLL_TuneZ2_M-50_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM   ZJETS  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/TPSKIM1.py 
#farmoutAnalysisJobs $1 --input-files-per-job=10  --input-dbs-path=/QCD_Pt-20_MuEnrichedPt-15_TuneZ2_7TeV-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM  QCD  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/TPSKIM1.py 


#farmoutAnalysisJobs $1 --input-files-per-job=10  --input-dbs-path=/QCD_Pt-20_MuEnrichedPt-10_TuneZ2_7TeV-pythia6/Summer11-PU_S3_START42_V11-v2/AODSIM  QCDLOW  $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/Skims/SKIM.py 

rm TPSKIM.py