#!/bin/sh

preselection='pt1>20&&pt2>20&&vertices>0&&diLeptons==0&&lPFIsoDB<0.1&&tauIso<1.8&&tightMuons<=1&&tightElectrons==0'
inclselection='pt1>20&&pt2>20&&vertices>0&&diLeptons==0&&lPFIsoDB<0.1&&tauIso<1.8&&tightMuons<=1&&tightElectrons==0'
wselection='mt1>70'
signalselection='mt1<30'
qcdselection='pt1>20&&pt2>20&&vertices>0&&diLeptons==0&&lPFIsoDB>0.2&&tauIso<1.3&&charge!=0&&mt1<30&&lTrigger>0&&tauTrigger>0'
relaxedSelection='pt1>20&&pt2>20&&vertices>0&&mt1<30&&lTrigger>0&&tauTrigger>0'
embWeight='__CORR__*EmbPtWeight*HLT_Mu17_Mu8_fired'
luminosity=10000. #10 fb^-1
direc='/nfs_scratch/laura/htautau_test/'
zttScale=1.
qcdfactor=1. 
topSF=1.
#

binning='binningHighStat=0.,10.,20.,30.,40.,50.,60.,70.,80.,90.,100.,110.,120.,130.,140.,150.,160.,170.,180.,190.,200.,225.,250.,275.,300.,325.,350. binningLowStat=0.,20.,40.,60.,80.,100.,120.,140.,160.,180.,200.,250.,300.,350.' 
mkdir datacards



#binning='binningHighStat=0.,5.,10.,15.,20.,25.,30.,35.,40.,45.,50.,55.,60.,65.,70.,75.,80.,85.,90.,95.,100.,105.,110.,115.,120.,125.,130.,135.,140.,145.,150.,155.,160.,165.,170.,175.,180.,185.,190.,195.,200.,210.,220.,230.,240.,250.,260.,270.,280.,290.,300.,310.,320.,330.,340.,350. binningLowStat=0.,20.,40.,60.,80.,100.,120.,140.,160.,180.,200.,250.,300.,350.' 

binning='binningHighStat=0.,20.,40.,60.,80.,100.,120.,140.,160.,180.,200.,250.,300.,350. binningLowStat=0.,20.,40.,60.,80.,100.,120.,140.,160.,180.,200.,250.,300.,350.' 


MakeDataCardZTT channel='muTau' shifts='Tau','Jet' qcdFile=$direc'../qcd.root' zttFile=$direc'ZTT.root' zllFile=$direc'ZTT.root' wFile=$direc'WJets.root' vvFile=$direc'WZ.root' topFile=$direc'TTJets.root' inclselection=$inclselection preselection=$preselection  wselection=$wselection  signalselection='mt1<30'   qcdselection=$qcdselection luminosityErr=0.045 qcdfactor=$qcdfactor qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075  topSF=$topSF 	muID=1.00 muIDErr=0.01 eleID=0.0 eleIDErr=0.0 tauID=1.0 tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17    bitmask=1,0,0,0 weight='__WEIGHT__'  luminosity=$luminosity  variable='svMass' bins=25 min=0 max=350 outputFile='datacards/htt_mt.inputs-sm-13TeV.root' $binning 


#blinding='(!(svMass>100&&svMass<160))'
